default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>

development:
  <<: *default
  database: wariko_development

test:
  <<: *default
  database: wariko_test

production:
  <<: *default
  database: wariko_production
  password: <%= ENV['WARIKO_DATABASE_PASSWORD'] %>
